# Generated by Django 2.1.15 on 2020-08-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PointID', models.IntegerField()),
                ('PointName', models.CharField(max_length=300)),
                ('UnitName', models.CharField(max_length=20)),
                ('SystemName', models.CharField(max_length=50)),
                ('Operation', models.CharField(max_length=50)),
                ('PointDescription', models.CharField(max_length=500)),
                ('PointType', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tblTrendAnalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PointID', models.IntegerField()),
                ('PointDate', models.IntegerField()),
                ('ActualValue', models.IntegerField()),
            ],
        ),
    ]
